services:
  - type: web
    name: backend-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ProyectoDetectorEtiquetas.wsgi:application"
    region: us-central
    plan: free
    runtime: python
    pythonVersion: 3.9
    disk:
      size: 1GB
      mountPath: /var/lib/data
    envVars:
      - key: SECRET_KEY
        value: "django-insecure-6@ewl$@+$o--$p6r)=gh!taot7eduz$^x#y4bhpkq$&1rsr3zl"
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        value: "postgres://usuario:contraseña@ip_publica:puerto/nombre_base_de_datos"
