# Generated by Django 5.1.4 on 2025-01-06 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appDetectorEtiquetas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagen",
            name="fecha_procesamiento",
            field=models.DateTimeField(
                auto_now_add=True, default=datetime.datetime.now
            ),
            preserve_default=False,
        ),
    ]
