# Generated by Django 5.1.4 on 2025-01-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appDetectorEtiquetas", "0002_imagen_fecha_procesamiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagen",
            name="imagen",
            field=models.CharField(max_length=255),
        ),
    ]
